### ISSUE TITLE
Consistencia

### ISSUE THREAD

**Issue by Lordkaito** [HumbertoDevelop/MovieApp-Js#1]
https://github.com/HumbertoDevelop/MovieApp-Js/blob/c806ba047bec8d3bd0613d6e00498f128cf7a20e/assets/css/style.css#L53-L59

Uno de las primeras mejoras que te recomiendo, es que seas consistente.
Aqui por ejemplo, estás usando 3 unidades diferentes, para el posicionamiento utilizas `right: 40px`, para el padding `padding: 0.66em` y para el tamaño de fuente usas `font-size: 1.5rem`.

- [x] Te aconsejo que uses una sola unidad de medida para todo tu projecto, lo cual desenvocará en un proyecto más profesional, organizado y sobre todo más fácil de modificar en el futuro. Y si me preguntas, yo utilizaria unidades relativas en lugar de pixeles, de esa forma tu página es incluso más responsiva.

**Comment by HumbertoDevelop** [comment]
Comprendo, tengo entendido que el rem se usa para las letras y el em para posicionamientos de cajas, asi lo hare. Dejare los px a un lado. Gracias por tu consejo.

**Comment by HumbertoDevelop** [comment]
problema resuelto, medidas em y rem colocadas en todos bloques de codigo

**Comment by HumbertoDevelop** [comment]
resuelto.
