### ISSUE TITLE
Comentarios innecesarios

### ISSUE THREAD

**Issue by Lordkaito** [HumbertoDevelop/MovieApp-Js#2]
https://github.com/HumbertoDevelop/MovieApp-Js/blob/c806ba047bec8d3bd0613d6e00498f128cf7a20e/assets/css/style.css#L69
https://github.com/HumbertoDevelop/MovieApp-Js/blob/c806ba047bec8d3bd0613d6e00498f128cf7a20e/assets/css/style.css#L204

También te aconsejo que elimines todos los comentarios innecesarios de tu código. Aquí te dejé solo un par como referencia, pero sería bueno que revises el codigo entero en busca de comentarios innecesario para que tu codigo se vea más profesional.

**Comment by HumbertoDevelop** [comment]
comentarios innecesarios eliminados 💻

**Comment by HumbertoDevelop** [comment]
resuelto
