### ISSUE TITLE
Selectores repetidos

### ISSUE THREAD

**Issue by Lordkaito** [HumbertoDevelop/MovieApp-Js#3]
https://github.com/HumbertoDevelop/MovieApp-Js/blob/c806ba047bec8d3bd0613d6e00498f128cf7a20e/assets/css/style.css#L135
https://github.com/HumbertoDevelop/MovieApp-Js/blob/c806ba047bec8d3bd0613d6e00498f128cf7a20e/assets/css/style.css#L141

Con respecto a selectores, repetirlos puede parecer una buena idea para ser más específico, pero intenta no usar selectores muy grandes que solo ensucian tu código, en lugar de eso puedes usar los `id` o `class` en el respectivo elemento HTML para ser específico. Recuerda que un mismo elemento HTML puede tener distintas clases, por lo que puedes aplicar distintos estilos al mismo elemento sin necesidad de repetir su selector. Y si quieres algo único, tienes el `id` disponible.
- [x] Evita selectores enormes y repetidos

**Comment by HumbertoDevelop** [comment]
Problema resuelto

**Comment by HumbertoDevelop** [comment]
resuelto
