### ISSUE TITLE
Padding excesivo

### ISSUE THREAD

**Issue by Lordkaito** [HumbertoDevelop/MovieApp-Js#4]
https://github.com/HumbertoDevelop/MovieApp-Js/blob/c806ba047bec8d3bd0613d6e00498f128cf7a20e/assets/css/style.css#L184-L188

Cuando estás estilizando un elemento, realmente no quieres utilizar padding excesivo, para eso puedes utilizar el margin. Recuerda que cuando usas padding, lo que estás acciendo es que la zona clickeable de ese elemento aumente, no solo la "distancia" de un elemento a otro. Esto puede ser perjudicial si quieres hacer click en ese elemento luego o en algun elemento hijo. 
Si lo que quieres es añadir separación entre elementos, puedes usar `margin` o bien `display: flex` o `display: grid` y darles el s

- [x] #9

**Comment by HumbertoDevelop** [comment]
Problema resuelto
