### ISSUE TITLE
Console.log

### ISSUE THREAD

**Issue by Lordkaito** [HumbertoDevelop/MovieApp-Js#5]
https://github.com/HumbertoDevelop/MovieApp-Js/blob/c806ba047bec8d3bd0613d6e00498f128cf7a20e/assets/js/app.js#L35-L37

Cuando estás preparando un proyecto, siempre es buena idea hacer `console.log`  de alguna funcionalidad para asegurarte que funciona, sin embargo, cuando vas a dar un producto final, no es buena idea mantener el `console.log`. Recuerda que a través de el das información que al usuario probablemente no le interese o no necesite, y lo más importante, das información sobre tu página a cualquiera que lo vea. Lo mejor es quitarle ese privilegio a cualquier usuario porque siempre te puedes encontrar con alguien que quiere lastimar o dañar tu proyecto.

- [x] Evita usar `console.log` en el proyecto final

**Comment by HumbertoDevelop** [comment]
resuelto
