### ISSUE TITLE
Uso de alert

### ISSUE THREAD

**Issue by Lordkaito** [HumbertoDevelop/MovieApp-Js#7]
https://github.com/HumbertoDevelop/MovieApp-Js/blob/c806ba047bec8d3bd0613d6e00498f128cf7a20e/assets/js/app.js#L173

La función `alert()` es muy básica en JavaScript, pero a día de hoy no es muy recomendable usarla para dar un mensaje al usuario, por distintos motivos:
1. Interrumpe la carga del resto de código mientras la alerta está en la pantalla.
2. Da mala experiencia al usuario pues una alerta siempre es molesta.
3. Si por algún motivo no se ejecuta o lo hace mal, puede provocar que tu código se rompa evitando ver el resto del contenido de la página.

En lugar de usar la función `alert()` siempre es más recomendable usar un modal propio que puedes construir personalizado para que se reproduzca cuando necesites hacer saber algo al usuario.

- [ ] Evita usar la función `alert()` en el código final.

**Comment by HumbertoDevelop** [comment]
modal personalizado añadido
